package com.example.luftkvalitet.network

class AnytimeResultObj (

    val date: String,
    val femman_airpressure: String,
    val mobil2_pm10: String,
    val mobil2_no2: String,
    val mobil2_nox: String,
    val hagasodra_pm10: String,
    val lejonet_rain: String,
    val femman_nox: String,
    val lejonet_temp: String,
    val femman_windspeed: String,
    val lejonet_rh: String,
    val mobil3_nox: String,
    val femman_pm10: String,
    val mobil3_pm10: String,
    val femman_temp: String,
    val femman_rain: String,
    val lejonet_windspeed: String,
    val femman_o3: String,
    val mobil3_no2: String,
    val haganorra_nox: String,
    val femman_winddir: String,
    val lejonet_globrad: String,
    val hagasodra_pm25: String,
    val haganorra_no2: String,
    val femman_rh: String,
    val lejonet_airpressure: String,
    val femman_pm25: String,
    val femman_no2: String,
    val time: String,
    val mobil1_nox: String,
    val femman_globrad: String,
    val mobil1_no2: String,
    val lejonet_winddir: String,
    val mobil1_pm10: String ) {}